theme: jekyll-theme-hacker
title: OIBP
email: xkrupprubu@github.com
description: 'A sarcastic story'
github_username: xkrupprubu
future: true
excerpt_separator: '---'
gems:
    - jekyll-redirect-from
    - jekyll-sitemap
    - jekyll-seo-tag
    - jekyll-feed
    - jekyll-toc
    - jemoji
sass:
    style: compressed
exclude:
    - node_modules
    - README.md
    - LICENSE.md
    - CNAME
    - Gemfile
    - Gemfile.lock
    - Gruntfile.js
    - package.json
    - script
    - spec
include:
    - _pages
